
$my_script = <<-SCRIPT
SCRIPT

Vagrant.configure('2') do |config|

  config.vm.box = 'ubuntu/bionic64'

    config.vm.define 'mysqldb' do |mysql|
	end

	config.vm.define 'phpweb' do |phpweb|
		phpweb.vm.network 'forwarded_port', guest: 8888, host: 8888
		phpweb.vm.network 'public_network', ip: '192.168.0.22'
		phpweb.vm.provision 'shell', 
		  inline: 'apt-get update && apt-get install -y puppet'
	  
		phpweb.vm.provision "puppet" do |puppet|	  
		  puppet.manifests_path = "./configs/manifests"
		  puppet.manifest_file = "phpweb.pp"
	
		end
    end
			
    config.vm.define 'mysqlserver' do |mysqlserver|
	  mysqlserver.vm.network 'public_network', ip: '192.168.0.23'
	  mysqlserver.vm.provision 'shell',
	    inline: 'cat /vagrant/configs/id_bionic.pub >> /home/vagrant/.ssh/authorized_keys'
    end

    config.vm.define 'ansible_machine' do |ansible_machine|
	  ansible_machine.vm.network 'public_network', ip: '192.168.0.20'

	  ansible_machine.vm.provision 'shell',
	    inline: 'cp /vagrant/id_bionic /home/vagrant && \
		         chmod 600 /home/vagrant/id_bionic && \
				 chown vagrant:vagrant /home/vagrant/id_bionic'

	  ansible_machine.vm.provision 'shell', 
        inline: 'apt update && \
		         apt install software-properties-common && \
		         apt-add-repository --yes --update ppa:ansible/ansible && \
		         apt install -y ansible && \
				 ansible --version'
    end
end
