
$my_script = <<-SCRIPT
apt-get update && \
apt-get install -y mysql-server
SCRIPT

Vagrant.configure('2') do |config|

  config.vm.box = 'ubuntu/bionic64'

  config.vm.define 'mysqldb' do |mysql|
    mysql.vm.network 'forwarded_port', guest: 80, host: 8080
    mysql.vm.network 'public_network', ip: '192.168.0.10'
    mysql.vm.provision 'shell', 
	  inline: 'cat /configs/id_bionic.pub >> /home/vagrant/.ssh/authorized_keys'
    mysql.vm.provision 'shell', inline: $my_script
    mysql.vm.synced_folder './configs', '/configs'
    mysql.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.define 'phpweb' do |phpweb|
    phpweb.vm.network 'forwarded_port', guest: 8888, host: 8888
    phpweb.vm.network 'public_network', ip: '192.168.0.20'
    phpweb.vm.provision 'shell', 
	  inline: 'apt-get update && apt-get install -y puppet'
   
    phpweb.vm.provision "puppet" do |puppet|	  
	  puppet.manifests_path = "./configs/manifests"
	  puppet.manifest_file = "phpweb.pp"
    end
  end
end
